<?php

namespace AppBundle\Repository;

/**
 * CellarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CellarRepository extends \Doctrine\ORM\EntityRepository
{
}
